-- Snowflake Enterprise Cloud Warehouse Schema
-- Retail Demand Forecasting & Inventory Optimization Platform

CREATE DATABASE IF NOT EXISTS RETAIL_DW;
CREATE SCHEMA IF NOT EXISTS RETAIL_DW.ANALYTICS;
USE SCHEMA RETAIL_DW.ANALYTICS;

CREATE OR REPLACE TABLE DIM_STORES (
    STORE_ID VARCHAR(20) PRIMARY KEY,
    STATE_ID VARCHAR(10) NOT NULL,
    STORE_NAME VARCHAR(100),
    REGION VARCHAR(50)
);

CREATE OR REPLACE TABLE DIM_CATEGORIES (
    CAT_ID VARCHAR(30) PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_DEPARTMENTS (
    DEPT_ID VARCHAR(30) PRIMARY KEY,
    CAT_ID VARCHAR(30) NOT NULL,
    DEPARTMENT_NAME VARCHAR(100)
);

CREATE OR REPLACE TABLE DIM_PRODUCTS (
    ITEM_ID VARCHAR(50) PRIMARY KEY,
    DEPT_ID VARCHAR(30) NOT NULL,
    CAT_ID VARCHAR(30) NOT NULL,
    PRODUCT_NAME VARCHAR(150),
    UNIT_COST NUMBER(10, 2) DEFAULT 0.00
);

CREATE OR REPLACE TABLE DIM_CALENDAR (
    DATE_STR VARCHAR(10) PRIMARY KEY,
    WM_YR_WK NUMBER(38, 0) NOT NULL,
    WEEKDAY VARCHAR(15) NOT NULL,
    WDAY NUMBER(38, 0) NOT NULL,
    MONTH NUMBER(38, 0) NOT NULL,
    YEAR NUMBER(38, 0) NOT NULL,
    D_ID VARCHAR(10) NOT NULL,
    EVENT_NAME_1 VARCHAR(50),
    EVENT_TYPE_1 VARCHAR(50),
    EVENT_NAME_2 VARCHAR(50),
    EVENT_TYPE_2 VARCHAR(50),
    SNAP_CA NUMBER(38, 0) DEFAULT 0,
    SNAP_TX NUMBER(38, 0) DEFAULT 0,
    SNAP_WI NUMBER(38, 0) DEFAULT 0,
    IS_HOLIDAY NUMBER(38, 0) DEFAULT 0
);

CREATE OR REPLACE TABLE FACT_SALES (
    ID VARCHAR(80),
    ITEM_ID VARCHAR(50) NOT NULL,
    DEPT_ID VARCHAR(30),
    CAT_ID VARCHAR(30),
    STORE_ID VARCHAR(20) NOT NULL,
    STATE_ID VARCHAR(10),
    DATE_STR VARCHAR(10) NOT NULL,
    SALES_UNITS NUMBER(38, 0) NOT NULL,
    PRIMARY KEY (ITEM_ID, STORE_ID, DATE_STR)
);

CREATE OR REPLACE TABLE FACT_PRICES (
    STORE_ID VARCHAR(20) NOT NULL,
    ITEM_ID VARCHAR(50) NOT NULL,
    WM_YR_WK NUMBER(38, 0) NOT NULL,
    SELL_PRICE NUMBER(10, 2) NOT NULL,
    PRIMARY KEY (STORE_ID, ITEM_ID, WM_YR_WK)
);

CREATE OR REPLACE TABLE FACT_FORECAST_RESULTS (
    ID NUMBER(38, 0) AUTOINCREMENT PRIMARY KEY,
    FORECAST_DATE VARCHAR(10) NOT NULL,
    ITEM_ID VARCHAR(50) NOT NULL,
    STORE_ID VARCHAR(20) NOT NULL,
    MODEL_USED VARCHAR(50) NOT NULL,
    ACTUAL_DEMAND NUMBER(10, 2),
    FORECAST_DEMAND NUMBER(10, 2) NOT NULL,
    CONFIDENCE_LOWER NUMBER(10, 2),
    CONFIDENCE_UPPER NUMBER(10, 2),
    FORECAST_ERROR NUMBER(10, 2),
    HORIZON_DAYS NUMBER(38, 0) NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE FACT_INVENTORY_RECOMMENDATIONS (
    ID NUMBER(38, 0) AUTOINCREMENT PRIMARY KEY,
    EVALUATION_DATE VARCHAR(10) NOT NULL,
    ITEM_ID VARCHAR(50) NOT NULL,
    STORE_ID VARCHAR(20) NOT NULL,
    CURRENT_INVENTORY NUMBER(38, 0) NOT NULL,
    AVERAGE_DAILY_DEMAND NUMBER(10, 2) NOT NULL,
    DEMAND_STD_DEV NUMBER(10, 2) NOT NULL,
    LEAD_TIME_DAYS NUMBER(38, 0) NOT NULL,
    SAFETY_STOCK NUMBER(38, 0) NOT NULL,
    REORDER_POINT NUMBER(38, 0) NOT NULL,
    FORECAST_DEMAND_LT NUMBER(10, 2) NOT NULL,
    RECOMMENDED_ORDER_QTY NUMBER(38, 0) NOT NULL,
    DAYS_OF_SUPPLY NUMBER(10, 2) NOT NULL,
    INVENTORY_STATUS VARCHAR(50) NOT NULL,
    RISK_LEVEL VARCHAR(20) NOT NULL,
    STOCKOUT_RISK_PCT NUMBER(5, 2) NOT NULL,
    OVERSTOCK_RISK_PCT NUMBER(5, 2) NOT NULL,
    SUGGESTED_REPLENISHMENT_DATE VARCHAR(10),
    ESTIMATED_ORDER_COST NUMBER(12, 2),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
